[package]
name = "mouse-steering"
version = "3.0.0"
edition = "2021"

[dependencies]
directories = "5.0.1"
minifb = "0.26.0"
mouse_position = "0.1.3"
serde = { version = "1.0.202", features = ["derive"] }
toml = "0.8.13"
vigem-client = "0.1.4"
