screen_width = 1280
screen_height = 720

[steering_config]
enabled = true
toggle_key = "Z" # You can read all of the keycodes below
precise_input = true
snap_input = true
snap_threshold = 0.1 # Ranges from 0.0 to 1.0
edge_scaling = false
scaling_threshold = 0.5 # Ranges from 0.0 to 1.0

[throttle_config]
enabled = true
toggle_key = "X" # You can read all of the keycodes below
precise_input = true
snap_input = true
snap_threshold = 0.1 # Ranges from 0.0 to 1.0
edge_scaling = false
scaling_threshold = 0.5 # Ranges from 0.0 to 1.0

# List of keycodes
# Key0
# Key1
# Key2
# Key3
# Key4
# Key5
# Key6
# Key7
# Key8
# Key9
# A
# B
# C
# D
# E
# F
# G
# H
# I
# J
# K
# L
# M
# N
# O
# P
# Q
# R
# S
# T
# U
# V
# W
# X
# Y
# Z
# F1
# F2
# F3
# F4
# F5
# F6
# F7
# F8
# F9
# F10
# F11
# F12
# Escape
# Space
# LControl
# RControl
# LShift
# RShift
# LAlt
# RAlt
# Command
# LOption
# ROption
# LMeta
# RMeta
# Enter
# Up
# Down
# Left
# Right
# Backspace
# CapsLock
# Tab
# Home
# End
# PageUp
# PageDown
# Insert
# Delete

# The following keys have not been tested on MacOS!
# Numpad keys which have not been implemented: NumpadSeparator NumLock
# Numpad0
# Numpad1
# Numpad2
# Numpad3
# Numpad4
# Numpad5
# Numpad6
# Numpad7
# Numpad8
# Numpad9
# NumpadSubtract
# NumpadAdd
# NumpadDivide
# NumpadMultiply

# The following keys names represent the position of the key in a US keyboard
# not the sign value. In a different keyboards and OS the position can vary.
# Grave
# Minus
# Equal
# LeftBracket
# RightBracket
# BackSlash
# Semicolon
# Apostrophe
# Comma
# Dot
# Slash